### ISSUE TITLE
Add link to GitHub repo in app

### ISSUE THREAD

**Issue by vknabel** [vknabel/puffery#49]
A link to this repository within the app would be great.
It should be located somewhere inside the settings sheet.

**Comment by vknabel** [comment]
There is a unnamed section for "legal stuff". Either create a new row here or create a new Section within the Acknowledgments page.

Just adding the Englisch localization is totally fine!

On click it should directly open the GitHub repository. Therefore: no disclosure indicator (>). Either use a [SF Symbol](https://developer.apple.com/design/human-interface-guidelines/sf-symbols/overview/) (like `safari` or an arrow within a square) on the right end of the row, or no icon at all.

**Comment by InsanelyHarsh** [comment]
I would like to take this issue.

**Comment by vknabel** [comment]
Sure, thanks @InsanelyHarsh!
If you have any questions or need a starting point, feel free to ask.

**Comment by vknabel** [comment]
Thanks for the contribution in #73. Currently new builds are being built. After a short review time by apple, the [TestFlight build will be publicly available](https://testflight.apple.com/join/066lEjQN).

**Comment by InsanelyHarsh** [comment]
Hi, @vknabel 
I am starting my Open Source journey with HACKTOBERFEST & this is my PR. Can you add "HACKTOBERFEST-ACCEPTED"
tag to issue and Repo.

**Comment by vknabel** [comment]
@InsanelyHarsh that's great to hear. Congratulations to your second PR!
I added the `hacktoberfest` label to the repo and this issue and `hacktoberfest-accepted` to your pull request, approved and merged it. On [hacktoberfest.com/profile](https://hacktoberfest.com/profile/) you should see this PR listed as waiting. After 7 days it should turn into accepted automatically. No worries.

In some cases it takes a few minutes for Hacktoberfest to check, but once it detected the merge, you should receive an email. 👍

**Comment by vknabel** [comment]
In case you feel like a feature is missing or if you stumbled upon a bug, feel free to open an issue. I'll try to estimate how hard the feature/fix is and if you wish, you can create another PR. I'll add the labels appropriately.

Also feel free to update the documentation if it wasn't clear enough, outdated or lacks information.
