### ISSUE TITLE
Error building server: Value of type 'User' has no member 'wait'

### ISSUE THREAD

**Issue by comiclandapp** [vknabel/puffery#71]
in /Users/tony/Downloads/puffery-main/PufferyServer/Tests/AppTests/Application+Seeding.swift

Stumbled upon your repo today. Very interesting. Using Xcode Version 13.3 beta 2 (13E5095k) to build. Thanks for the help.

Best regards.

**Comment by vknabel** [comment]
Hi @comiclandapp, thanks for feedback. It seems like some Unit tests were outdated 😱

I just updated the `main`-branch and also added some more details to the [CONTRIBUTING.md](https://github.com/vknabel/puffery/blob/main/CONTRIBUTING.md). In case you have any questions, feel free to ask!

**Comment by comiclandapp** [comment]
Cheers. Updated main and now:
`Dependencies could not be resolved because no versions of 'apollo-ios' match the requirement 0.49.0..<1.0.0 and root depends on 'apollo-ios' 0.49.0..<1.0.0.
`

**Comment by vknabel** [comment]
Hmm, that's weird. [apollo-ios@0.49.0](https://github.com/apollographql/apollo-ios/releases/tag/0.49.0) does actually exist.

Does a quitting and restarting Xcode help? Otherwise I could try updating the dependencies. Though this might take a few days.
